title: hoshihoshi
description: my memo
remote_theme: riggraz/no-style-please
baseurl: "/blog"

theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
